POST http://localhost:3002/client/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbGt5OHlsc2YwMDAwOWs4ZzE5NjVxZTdtIiwiY2xpZW50SWQiOiJjbGw2dzczbDQwMDA0OWtwbjNibm1xcmM3IiwiaWF0IjoxNjkxNzc2NzUyLCJleHAiOjE2OTQzNjg3NTJ9.kqs4FizkvU9RUzhzmYvwqI35PYPWf5H7cltA9gJ5pK4
